#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "rexml/document"

ROOT = File.expand_path("../..", __dir__)
ANDROID_RES = File.join(ROOT, "android/app/src/main/res")
IOS_APP = File.join(ROOT, "ios/ResetMotoReminders/ResetMotoReminders")
LOCALES = %w[en de es fr uk].freeze

IOS_ONLY = {
  "en" => {
    "action_done" => "Done",
    "ios_status_waiting_bluetooth" => "Checking Bluetooth…",
    "ios_status_scanning" => "Looking for a supported adapter…",
    "ios_status_discovering" => "Checking adapter…",
    "ios_status_motorcycle_connected" => "Motorcycle connected",
    "ios_connection_hint" => "Power the motorcycle and Bluetooth OBD adapter, then connect.",
    "ios_adapter_experimental" => "EXPERIMENTAL ADAPTER",
    "ios_disclaimer" => "Unofficial tool. Clearing codes does not repair faults. Resetting a reminder does not perform maintenance.",
    "ios_working" => "Working…",
    "ios_clear_confirmation_title" => "Clear confirmed trouble codes?",
    "ios_clear_confirmation_format" => "Clear %1$@? Diagnostic evidence will be erased. Existing faults are not repaired.",
    "ios_reset_confirmation_title" => "Reset service reminder?",
    "ios_motorcycle_title" => "Motorcycle",
    "ios_odometer_label" => "Odometer",
    "ios_dashboard_label" => "Dashboard",
    "ios_dashboard_supported" => "Supported dashboard recognized",
    "ios_fingerprint_format" => "Diagnostic fingerprint %1$@ is a compatibility check, not a fault code.",
    "ios_beta" => "BETA",
    "ios_clear_detail" => "Clears confirmed DTC memory after security access. It does not repair the underlying fault.",
    "ios_read_codes_first" => "Read and review the current trouble codes first.",
    "ios_dashboard_unit" => "Dashboard unit",
    "ios_unit_kilometres" => "Kilometres",
    "ios_unit_miles" => "Miles",
    "ios_interval" => "Interval",
    "ios_interval_help" => "Use 100-unit steps, from 100 to 25,500. Check that your motorcycle’s date is correct.",
    "ios_read_motorcycle_first" => "Read the motorcycle first so the current odometer is visible before confirmation.",
    "ios_interval_error" => "Enter a value from 100 to 25,500 in 100-unit steps.",
    "ios_current_odometer_format" => "Current odometer: %1$d km.",
    "ios_reset_confirmation_format" => "Set %1$@ %2$@ and %3$@. Check that your motorcycle’s date is correct.",
    "ios_background_closed" => "Connection closed when the app entered the background. Reconnect before continuing.",
    "ios_operation_interrupted" => "operation interrupted",
    "ios_operation_reading_motorcycle" => "Reading motorcycle",
    "ios_operation_reading_dtc" => "Reading trouble codes",
    "ios_operation_clearing_dtc" => "Clearing trouble codes",
    "ios_operation_resetting_service" => "Resetting service reminder",
    "ios_dashboard_responded" => "Motorcycle responded.",
    "ios_dtc_cleared" => "Confirmed trouble-code memory cleared. This does not repair a fault.",
    "ios_dtc_clear_blocked" => "Clear was refused before it could be confirmed.",
    "ios_dtc_clear_unverified" => "Clear may have run, but verification did not confirm an empty memory.",
    "ios_service_committed_format" => "Service reminder reset at %1$d km. Maintenance was not performed by the app.",
    "ios_service_blocked" => "Reset was refused before a complete reminder update was confirmed.",
    "ios_service_partial" => "Distance may be updated, but the date was not confirmed. Inspect the dashboard before retrying.",
    "ios_error_connect_first" => "Connect to the motorcycle first.",
    "ios_error_unsupported_layout" => "This adapter does not expose a supported Bluetooth connection.",
    "ios_error_invalid_identity" => "The adapter identification reply was not recognized.",
    "ios_error_timeout" => "The motorcycle did not answer in time.",
    "ios_error_ambiguous_write" => "The connection ended after a write. Its result is unknown—inspect the motorcycle before trying again.",
    "ios_error_disconnected" => "The adapter disconnected.",
    "ios_error_bluetooth_permission" => "Bluetooth permission is required to connect to the adapter.",
    "ios_error_bluetooth_off" => "Bluetooth is off.",
    "ios_error_ble_unsupported" => "Bluetooth Low Energy is not supported on this device.",
    "ios_error_connect_failed" => "Could not connect to the adapter.",
    "ios_error_setup_rejected" => "The adapter rejected setup command %1$@. Disconnect and try again.",
    "ios_error_dtc_count_mismatch" => "The motorcycle reported %1$d trouble code(s), but %2$d complete record(s) were received. Read again before clearing.",
    "ios_error_unrecognized_response" => "The motorcycle returned an unrecognized response. Nothing was written.",
    "ios_error_response_too_large" => "The adapter response was too large. Disconnect and try again."
  },
  "de" => {
    "action_done" => "Fertig",
    "ios_status_waiting_bluetooth" => "Bluetooth wird geprüft…",
    "ios_status_scanning" => "Unterstützter Adapter wird gesucht…",
    "ios_status_discovering" => "Adapter wird geprüft…",
    "ios_status_motorcycle_connected" => "Motorrad verbunden",
    "ios_connection_hint" => "Motorrad und Bluetooth-OBD-Adapter einschalten, dann verbinden.",
    "ios_adapter_experimental" => "EXPERIMENTELLER ADAPTER",
    "ios_disclaimer" => "Inoffizielles Werkzeug. Das Löschen von Fehlercodes repariert keine Fehler. Das Zurücksetzen einer Erinnerung führt keine Wartung durch.",
    "ios_working" => "Wird ausgeführt…",
    "ios_clear_confirmation_title" => "Bestätigte Fehlercodes löschen?",
    "ios_clear_confirmation_format" => "%1$@ löschen? Diagnosedaten werden entfernt. Bestehende Fehler werden nicht repariert.",
    "ios_reset_confirmation_title" => "Serviceerinnerung zurücksetzen?",
    "ios_motorcycle_title" => "Motorrad",
    "ios_odometer_label" => "Kilometerstand",
    "ios_dashboard_label" => "Instrument",
    "ios_dashboard_supported" => "Unterstütztes Instrument erkannt",
    "ios_fingerprint_format" => "Diagnosekennung %1$@ ist eine Kompatibilitätsprüfung, kein Fehlercode.",
    "ios_beta" => "BETA",
    "ios_clear_detail" => "Löscht bestätigte DTCs nach Sicherheitszugriff. Der zugrunde liegende Fehler wird nicht repariert.",
    "ios_read_codes_first" => "Aktuelle Fehlercodes zuerst lesen und prüfen.",
    "ios_dashboard_unit" => "Instrumenteinheit",
    "ios_unit_kilometres" => "Kilometer",
    "ios_unit_miles" => "Meilen",
    "ios_interval" => "Intervall",
    "ios_interval_help" => "Schritte zu 100, von 100 bis 25.500. Prüfe das Datum des Motorrads.",
    "ios_read_motorcycle_first" => "Motorrad zuerst lesen, damit der aktuelle Kilometerstand vor der Bestätigung sichtbar ist.",
    "ios_interval_error" => "Wert von 100 bis 25.500 in 100er-Schritten eingeben.",
    "ios_current_odometer_format" => "Aktueller Kilometerstand: %1$d km.",
    "ios_reset_confirmation_format" => "%1$@ %2$@ und %3$@ einstellen. Prüfe das Datum des Motorrads.",
    "ios_background_closed" => "Verbindung beim Wechsel in den Hintergrund geschlossen. Vor dem Fortfahren erneut verbinden.",
    "ios_operation_interrupted" => "Vorgang unterbrochen",
    "ios_operation_reading_motorcycle" => "Motorrad wird gelesen",
    "ios_operation_reading_dtc" => "Fehlercodes werden gelesen",
    "ios_operation_clearing_dtc" => "Fehlercodes werden gelöscht",
    "ios_operation_resetting_service" => "Serviceerinnerung wird zurückgesetzt",
    "ios_dashboard_responded" => "Motorrad hat geantwortet.",
    "ios_dtc_cleared" => "Bestätigter Fehlercodespeicher gelöscht. Ein Fehler wird dadurch nicht repariert.",
    "ios_dtc_clear_blocked" => "Löschen wurde abgelehnt, bevor es bestätigt werden konnte.",
    "ios_dtc_clear_unverified" => "Löschen wurde möglicherweise ausgeführt, aber ein leerer Speicher wurde nicht bestätigt.",
    "ios_service_committed_format" => "Serviceerinnerung bei %1$d km zurückgesetzt. Die App hat keine Wartung durchgeführt.",
    "ios_service_blocked" => "Zurücksetzen wurde abgelehnt, bevor die vollständige Änderung bestätigt wurde.",
    "ios_service_partial" => "Die Distanz kann geändert sein, das Datum wurde nicht bestätigt. Vor einem neuen Versuch das Instrument prüfen.",
    "ios_error_connect_first" => "Zuerst mit dem Motorrad verbinden.",
    "ios_error_unsupported_layout" => "Dieser Adapter stellt keine unterstützte Bluetooth-Verbindung bereit.",
    "ios_error_invalid_identity" => "Die Adapterantwort zur Identifizierung wurde nicht erkannt.",
    "ios_error_timeout" => "Das Motorrad hat nicht rechtzeitig geantwortet.",
    "ios_error_ambiguous_write" => "Die Verbindung endete nach einem Schreibvorgang. Das Ergebnis ist unbekannt—Motorrad vor einem neuen Versuch prüfen.",
    "ios_error_disconnected" => "Der Adapter wurde getrennt.",
    "ios_error_bluetooth_permission" => "Zum Verbinden ist die Bluetooth-Berechtigung erforderlich.",
    "ios_error_bluetooth_off" => "Bluetooth ist ausgeschaltet.",
    "ios_error_ble_unsupported" => "Bluetooth Low Energy wird auf diesem Gerät nicht unterstützt.",
    "ios_error_connect_failed" => "Verbindung zum Adapter fehlgeschlagen.",
    "ios_error_setup_rejected" => "Der Adapter lehnte den Einrichtungsbefehl %1$@ ab. Trennen und erneut versuchen.",
    "ios_error_dtc_count_mismatch" => "Das Motorrad meldete %1$d Fehlercode(s), aber %2$d vollständige Datensätze wurden empfangen. Vor dem Löschen erneut lesen.",
    "ios_error_unrecognized_response" => "Das Motorrad gab eine unbekannte Antwort zurück. Es wurde nichts geschrieben.",
    "ios_error_response_too_large" => "Die Adapterantwort war zu groß. Trennen und erneut versuchen."
  },
  "es" => {
    "action_done" => "Listo",
    "ios_status_waiting_bluetooth" => "Comprobando Bluetooth…",
    "ios_status_scanning" => "Buscando un adaptador compatible…",
    "ios_status_discovering" => "Comprobando el adaptador…",
    "ios_status_motorcycle_connected" => "Moto conectada",
    "ios_connection_hint" => "Enciende la moto y el adaptador OBD Bluetooth y, después, conecta.",
    "ios_adapter_experimental" => "ADAPTADOR EXPERIMENTAL",
    "ios_disclaimer" => "Herramienta no oficial. Borrar códigos no repara averías. Restablecer un aviso no realiza el mantenimiento.",
    "ios_working" => "Procesando…",
    "ios_clear_confirmation_title" => "¿Borrar los códigos de avería confirmados?",
    "ios_clear_confirmation_format" => "¿Borrar %1$@? Se eliminarán datos de diagnóstico. Las averías existentes no se reparan.",
    "ios_reset_confirmation_title" => "¿Restablecer el aviso de servicio?",
    "ios_motorcycle_title" => "Moto",
    "ios_odometer_label" => "Odómetro",
    "ios_dashboard_label" => "Cuadro",
    "ios_dashboard_supported" => "Cuadro compatible reconocido",
    "ios_fingerprint_format" => "La huella de diagnóstico %1$@ comprueba la compatibilidad; no es un código de avería.",
    "ios_beta" => "BETA",
    "ios_clear_detail" => "Borra la memoria DTC confirmada tras el acceso de seguridad. No repara la avería subyacente.",
    "ios_read_codes_first" => "Primero lee y revisa los códigos de avería actuales.",
    "ios_dashboard_unit" => "Unidad del cuadro",
    "ios_unit_kilometres" => "Kilómetros",
    "ios_unit_miles" => "Millas",
    "ios_interval" => "Intervalo",
    "ios_interval_help" => "Usa pasos de 100, de 100 a 25.500. Comprueba la fecha de la moto.",
    "ios_read_motorcycle_first" => "Lee primero la moto para ver el odómetro actual antes de confirmar.",
    "ios_interval_error" => "Introduce un valor entre 100 y 25.500 en pasos de 100.",
    "ios_current_odometer_format" => "Odómetro actual: %1$d km.",
    "ios_reset_confirmation_format" => "Establecer %1$@ %2$@ y %3$@. Comprueba la fecha de la moto.",
    "ios_background_closed" => "La conexión se cerró al pasar la app a segundo plano. Vuelve a conectar antes de continuar.",
    "ios_operation_interrupted" => "operación interrumpida",
    "ios_operation_reading_motorcycle" => "Leyendo la moto",
    "ios_operation_reading_dtc" => "Leyendo códigos de avería",
    "ios_operation_clearing_dtc" => "Borrando códigos de avería",
    "ios_operation_resetting_service" => "Restableciendo el aviso de servicio",
    "ios_dashboard_responded" => "La moto ha respondido.",
    "ios_dtc_cleared" => "Memoria de códigos confirmados borrada. Esto no repara una avería.",
    "ios_dtc_clear_blocked" => "El borrado fue rechazado antes de poder confirmarlo.",
    "ios_dtc_clear_unverified" => "Puede que se haya borrado, pero no se confirmó que la memoria quedara vacía.",
    "ios_service_committed_format" => "Aviso de servicio restablecido a los %1$d km. La app no realizó mantenimiento.",
    "ios_service_blocked" => "El restablecimiento fue rechazado antes de confirmar una actualización completa.",
    "ios_service_partial" => "Puede que la distancia se actualizara, pero la fecha no se confirmó. Revisa el cuadro antes de reintentar.",
    "ios_error_connect_first" => "Conecta primero con la moto.",
    "ios_error_unsupported_layout" => "Este adaptador no ofrece una conexión Bluetooth compatible.",
    "ios_error_invalid_identity" => "No se reconoció la respuesta de identificación del adaptador.",
    "ios_error_timeout" => "La moto no respondió a tiempo.",
    "ios_error_ambiguous_write" => "La conexión terminó después de escribir. El resultado es desconocido: revisa la moto antes de reintentar.",
    "ios_error_disconnected" => "El adaptador se desconectó.",
    "ios_error_bluetooth_permission" => "Se necesita permiso de Bluetooth para conectar con el adaptador.",
    "ios_error_bluetooth_off" => "Bluetooth está desactivado.",
    "ios_error_ble_unsupported" => "Este dispositivo no admite Bluetooth Low Energy.",
    "ios_error_connect_failed" => "No se pudo conectar con el adaptador.",
    "ios_error_setup_rejected" => "El adaptador rechazó el comando de configuración %1$@. Desconecta y vuelve a intentarlo.",
    "ios_error_dtc_count_mismatch" => "La moto indicó %1$d código(s), pero se recibieron %2$d registros completos. Lee de nuevo antes de borrar.",
    "ios_error_unrecognized_response" => "La moto devolvió una respuesta no reconocida. No se escribió nada.",
    "ios_error_response_too_large" => "La respuesta del adaptador era demasiado grande. Desconecta y vuelve a intentarlo."
  },
  "fr" => {
    "action_done" => "Terminé",
    "ios_status_waiting_bluetooth" => "Vérification du Bluetooth…",
    "ios_status_scanning" => "Recherche d’un adaptateur compatible…",
    "ios_status_discovering" => "Vérification de l’adaptateur…",
    "ios_status_motorcycle_connected" => "Moto connectée",
    "ios_connection_hint" => "Mettez la moto et l’adaptateur OBD Bluetooth sous tension, puis connectez-vous.",
    "ios_adapter_experimental" => "ADAPTATEUR EXPÉRIMENTAL",
    "ios_disclaimer" => "Outil non officiel. Effacer des codes ne répare pas les pannes. Réinitialiser un rappel n’effectue pas l’entretien.",
    "ios_working" => "Opération en cours…",
    "ios_clear_confirmation_title" => "Effacer les codes défaut confirmés ?",
    "ios_clear_confirmation_format" => "Effacer %1$@ ? Les données de diagnostic seront supprimées. Les pannes existantes ne seront pas réparées.",
    "ios_reset_confirmation_title" => "Réinitialiser le rappel d’entretien ?",
    "ios_motorcycle_title" => "Moto",
    "ios_odometer_label" => "Compteur",
    "ios_dashboard_label" => "Tableau de bord",
    "ios_dashboard_supported" => "Tableau de bord compatible reconnu",
    "ios_fingerprint_format" => "L’empreinte de diagnostic %1$@ vérifie la compatibilité ; ce n’est pas un code défaut.",
    "ios_beta" => "BÊTA",
    "ios_clear_detail" => "Efface la mémoire DTC confirmée après l’accès de sécurité. Cela ne répare pas la panne sous-jacente.",
    "ios_read_codes_first" => "Lisez et vérifiez d’abord les codes défaut actuels.",
    "ios_dashboard_unit" => "Unité du tableau de bord",
    "ios_unit_kilometres" => "Kilomètres",
    "ios_unit_miles" => "Miles",
    "ios_interval" => "Intervalle",
    "ios_interval_help" => "Utilisez des pas de 100, de 100 à 25 500. Vérifiez la date de la moto.",
    "ios_read_motorcycle_first" => "Lisez d’abord la moto pour afficher le compteur actuel avant confirmation.",
    "ios_interval_error" => "Saisissez une valeur de 100 à 25 500 par pas de 100.",
    "ios_current_odometer_format" => "Compteur actuel : %1$d km.",
    "ios_reset_confirmation_format" => "Définir %1$@ %2$@ et %3$@. Vérifiez la date de la moto.",
    "ios_background_closed" => "Connexion fermée lors du passage de l’app en arrière-plan. Reconnectez-vous avant de continuer.",
    "ios_operation_interrupted" => "opération interrompue",
    "ios_operation_reading_motorcycle" => "Lecture de la moto",
    "ios_operation_reading_dtc" => "Lecture des codes défaut",
    "ios_operation_clearing_dtc" => "Effacement des codes défaut",
    "ios_operation_resetting_service" => "Réinitialisation du rappel d’entretien",
    "ios_dashboard_responded" => "La moto a répondu.",
    "ios_dtc_cleared" => "Mémoire des codes confirmés effacée. Cela ne répare pas une panne.",
    "ios_dtc_clear_blocked" => "L’effacement a été refusé avant de pouvoir être confirmé.",
    "ios_dtc_clear_unverified" => "L’effacement a peut-être eu lieu, mais la mémoire vide n’a pas été confirmée.",
    "ios_service_committed_format" => "Rappel d’entretien réinitialisé à %1$d km. L’app n’a effectué aucun entretien.",
    "ios_service_blocked" => "La réinitialisation a été refusée avant confirmation d’une mise à jour complète.",
    "ios_service_partial" => "La distance peut avoir changé, mais la date n’a pas été confirmée. Vérifiez le tableau de bord avant de réessayer.",
    "ios_error_connect_first" => "Connectez-vous d’abord à la moto.",
    "ios_error_unsupported_layout" => "Cet adaptateur n’expose pas de connexion Bluetooth compatible.",
    "ios_error_invalid_identity" => "La réponse d’identification de l’adaptateur n’a pas été reconnue.",
    "ios_error_timeout" => "La moto n’a pas répondu à temps.",
    "ios_error_ambiguous_write" => "La connexion s’est terminée après une écriture. Le résultat est inconnu : vérifiez la moto avant de réessayer.",
    "ios_error_disconnected" => "L’adaptateur s’est déconnecté.",
    "ios_error_bluetooth_permission" => "L’autorisation Bluetooth est nécessaire pour se connecter à l’adaptateur.",
    "ios_error_bluetooth_off" => "Le Bluetooth est désactivé.",
    "ios_error_ble_unsupported" => "Bluetooth Low Energy n’est pas pris en charge sur cet appareil.",
    "ios_error_connect_failed" => "Impossible de se connecter à l’adaptateur.",
    "ios_error_setup_rejected" => "L’adaptateur a refusé la commande de configuration %1$@. Déconnectez-vous et réessayez.",
    "ios_error_dtc_count_mismatch" => "La moto a signalé %1$d code(s), mais %2$d enregistrement(s) complet(s) ont été reçus. Relisez avant d’effacer.",
    "ios_error_unrecognized_response" => "La moto a renvoyé une réponse non reconnue. Rien n’a été écrit.",
    "ios_error_response_too_large" => "La réponse de l’adaptateur était trop volumineuse. Déconnectez-vous et réessayez."
  },
  "uk" => {
    "action_done" => "Готово",
    "ios_status_waiting_bluetooth" => "Перевірка Bluetooth…",
    "ios_status_scanning" => "Пошук підтримуваного адаптера…",
    "ios_status_discovering" => "Перевірка адаптера…",
    "ios_status_motorcycle_connected" => "Мотоцикл підключено",
    "ios_connection_hint" => "Увімкніть мотоцикл і Bluetooth OBD-адаптер, потім підключіться.",
    "ios_adapter_experimental" => "ЕКСПЕРИМЕНТАЛЬНИЙ АДАПТЕР",
    "ios_disclaimer" => "Неофіційний інструмент. Стирання кодів не усуває несправності. Скидання нагадування не виконує техобслуговування.",
    "ios_working" => "Виконується…",
    "ios_clear_confirmation_title" => "Стерти підтверджені коди несправностей?",
    "ios_clear_confirmation_format" => "Стерти %1$@? Діагностичні дані буде видалено. Наявні несправності не буде усунуто.",
    "ios_reset_confirmation_title" => "Скинути нагадування про сервіс?",
    "ios_motorcycle_title" => "Мотоцикл",
    "ios_odometer_label" => "Одометр",
    "ios_dashboard_label" => "Панель приладів",
    "ios_dashboard_supported" => "Сумісну панель приладів розпізнано",
    "ios_fingerprint_format" => "Діагностичний відбиток %1$@ перевіряє сумісність і не є кодом несправності.",
    "ios_beta" => "БЕТА",
    "ios_clear_detail" => "Стирає підтверджену пам’ять DTC після доступу безпеки. Це не усуває основну несправність.",
    "ios_read_codes_first" => "Спочатку прочитайте й перевірте поточні коди несправностей.",
    "ios_dashboard_unit" => "Одиниця на панелі",
    "ios_unit_kilometres" => "Кілометри",
    "ios_unit_miles" => "Милі",
    "ios_interval" => "Інтервал",
    "ios_interval_help" => "Використовуйте крок 100, від 100 до 25 500. Перевірте дату мотоцикла.",
    "ios_read_motorcycle_first" => "Спочатку прочитайте мотоцикл, щоб побачити поточний одометр перед підтвердженням.",
    "ios_interval_error" => "Введіть значення від 100 до 25 500 із кроком 100.",
    "ios_current_odometer_format" => "Поточний одометр: %1$d км.",
    "ios_reset_confirmation_format" => "Установити %1$@ %2$@ і %3$@. Перевірте дату мотоцикла.",
    "ios_background_closed" => "З’єднання закрито після переходу застосунку у фоновий режим. Підключіться знову.",
    "ios_operation_interrupted" => "операцію перервано",
    "ios_operation_reading_motorcycle" => "Читання мотоцикла",
    "ios_operation_reading_dtc" => "Читання кодів несправностей",
    "ios_operation_clearing_dtc" => "Стирання кодів несправностей",
    "ios_operation_resetting_service" => "Скидання нагадування про сервіс",
    "ios_dashboard_responded" => "Мотоцикл відповів.",
    "ios_dtc_cleared" => "Пам’ять підтверджених кодів стерто. Це не усуває несправність.",
    "ios_dtc_clear_blocked" => "Стирання відхилено до його підтвердження.",
    "ios_dtc_clear_unverified" => "Стирання могло виконатися, але порожню пам’ять не підтверджено.",
    "ios_service_committed_format" => "Нагадування скинуто на %1$d км. Застосунок не виконав техобслуговування.",
    "ios_service_blocked" => "Скидання відхилено до підтвердження повного оновлення.",
    "ios_service_partial" => "Відстань могла оновитися, але дату не підтверджено. Перевірте панель перед повторною спробою.",
    "ios_error_connect_first" => "Спочатку підключіться до мотоцикла.",
    "ios_error_unsupported_layout" => "Цей адаптер не надає підтримуваного Bluetooth-з’єднання.",
    "ios_error_invalid_identity" => "Відповідь ідентифікації адаптера не розпізнано.",
    "ios_error_timeout" => "Мотоцикл не відповів вчасно.",
    "ios_error_ambiguous_write" => "З’єднання завершилося після запису. Результат невідомий — перевірте мотоцикл перед повторною спробою.",
    "ios_error_disconnected" => "Адаптер від’єднано.",
    "ios_error_bluetooth_permission" => "Для підключення до адаптера потрібен дозвіл Bluetooth.",
    "ios_error_bluetooth_off" => "Bluetooth вимкнено.",
    "ios_error_ble_unsupported" => "Цей пристрій не підтримує Bluetooth Low Energy.",
    "ios_error_connect_failed" => "Не вдалося підключитися до адаптера.",
    "ios_error_setup_rejected" => "Адаптер відхилив команду налаштування %1$@. Від’єднайтесь і спробуйте знову.",
    "ios_error_dtc_count_mismatch" => "Мотоцикл повідомив %1$d код(ів), але отримано %2$d повних записів. Прочитайте знову перед стиранням.",
    "ios_error_unrecognized_response" => "Мотоцикл повернув нерозпізнану відповідь. Нічого не записано.",
    "ios_error_response_too_large" => "Відповідь адаптера була завеликою. Від’єднайтесь і спробуйте знову."
  }
}.freeze

INFO = {
  "en" => "Connects to a supported Bluetooth OBD adapter to read motorcycle diagnostics and reset the service reminder.",
  "de" => "Stellt eine Verbindung zu einem unterstützten Bluetooth-OBD-Adapter her, um Motorraddiagnosen zu lesen und die Serviceerinnerung zurückzusetzen.",
  "es" => "Se conecta a un adaptador OBD Bluetooth compatible para leer diagnósticos de la moto y restablecer el aviso de servicio.",
  "fr" => "Se connecte à un adaptateur OBD Bluetooth compatible pour lire le diagnostic de la moto et réinitialiser le rappel d’entretien.",
  "uk" => "Підключається до підтримуваного Bluetooth OBD-адаптера, щоб читати діагностику мотоцикла та скидати нагадування про сервіс."
}.freeze

def android_strings(path)
  document = REXML::Document.new(File.read(path, encoding: "UTF-8"))
  REXML::XPath.match(document, "/resources/string").each_with_object({}) do |node, values|
    value = node.texts.map(&:value).join
    value = value.gsub("\\'", "'").gsub(/%(\d+)\$s/, '%\1$@')
    values[node.attributes["name"]] = value
  end
end

def escaped(value)
  value.gsub("\\", "\\\\").gsub('"', '\\"').gsub("\n", "\\n")
end

base = android_strings(File.join(ANDROID_RES, "values/strings.xml"))

LOCALES.each do |locale|
  localized = locale == "en" ? {} : android_strings(File.join(ANDROID_RES, "values-#{locale}/strings.xml"))
  values = base.merge(localized).merge(IOS_ONLY.fetch(locale))
  directory = File.join(IOS_APP, "#{locale}.lproj")
  FileUtils.mkdir_p(directory)
  localizable = values.sort.map { |key, value| "\"#{key}\" = \"#{escaped(value)}\";" }.join("\n") + "\n"
  info = <<~STRINGS
    "CFBundleDisplayName" = "Reset Moto Reminders";
    "NSBluetoothAlwaysUsageDescription" = "#{escaped(INFO.fetch(locale))}";
  STRINGS
  File.write(File.join(directory, "Localizable.strings"), localizable)
  File.write(File.join(directory, "InfoPlist.strings"), info)
end

puts "Generated iPhone localizations for #{LOCALES.join(', ')}"
